spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guiguselection
    username: guiguselection
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update